Cap python-ldap below 3.4.0
apel/ssm pull request #193
Opened 2022-05-24 07:31 UTC by gregcorbett

python-ldap-3.4.0 dropped support for Python 2: https://github.com/python-ldap/python-ldap/releases/tag/python-ldap-3.4.0

2022-06-20 10:29 UTC, tofu-rocketry requested changes

2022-06-20 11:28 UTC, gregcorbett commented on requirements.txt
> +python-ldap<3.4.0
Added :)

2022-06-20 12:08 UTC, tofu-rocketry approved these changes

2022-06-20 12:09 UTC, merged

2023-06-29 09:57 UTC, tofu-rocketry commented
@gregcorbett Could you tidy up your branch for this?