else case and return added to issue 242
apel/ssm pull request #247
Opened 2023-08-01 08:49 UTC by DanielPerkins7

resolve #242

2023-08-02 10:31 UTC, tofu-rocketry requested changes

2023-08-02 10:31 UTC, tofu-rocketry commented on ssm/ssm2.py
> +            return None
Can you add a comment as to why we're doing this please?

2023-09-18 10:16 UTC, tofu-rocketry approved these changes

2023-09-18 10:19 UTC, rowan04 requested changes

2023-09-18 10:19 UTC, rowan04 commented on ssm/ssm2.py
> +
This line could do with removing, its flagging up on codeclimate

2023-09-18 10:21 UTC, RedProkofiev approved these changes
the comment is indeed well written

2023-09-18 10:36 UTC, merged