Cap version of certifi used below 2020.4.5.2
apel/ssm pull request #264
Opened 2023-09-18 14:04 UTC by gregcorbett

- 2020.4.5.2 dropped Python 2 support, https://github.com/certifi/python-certifi/commit/5efdd48f719d9c3c7c8f9a812da2256d088eab78
- `certifi` is used by `requests`, which is used by `argo-ams-library`

2023-09-18 14:34 UTC, tofu-rocketry requested changes

2023-09-18 14:34 UTC, tofu-rocketry commented on requirements.txt
> +certifi<2020.4.5.2 # Used by AMS (via requests), 2020.4.5.2 dropped support for Python 2
```suggestion
certifi<2020.4.5.2  # Used by AMS (via requests), 2020.4.5.2 dropped support for Python 2
```
Double spaces before comments (like Python code), please.

2023-09-18 14:39 UTC, rowan04 approved these changes
lgtm

2023-09-18 14:48 UTC, gregcorbett commented
FYI: I have also opened https://github.com/ARGOeu/argo-ams-library/pull/164.

2023-09-18 14:57 UTC, tofu-rocketry approved these changes

2023-09-18 15:01 UTC, merged

2023-09-26 10:22 UTC, gregcorbett commented
> FYI: I have also opened [ARGOeu/argo-ams-library#164](https://github.com/ARGOeu/argo-ams-library/pull/164).

This has been merged.