Nick 123
apel/ssm pull request #279
Opened 2023-11-02 18:15 UTC by RedProkofiev

(Will) Resolve #123 
UNFINISHED

This build script is meant to deprecate the RPM and Deb build scripts, and move over to a single build script for Deb and RPM systems using FPM.  Deb works fine, which makes sense, as it's an adapted version of the original Deb build.  RPM runs into a mildly mysterious issue:
```Process failed: rpmbuild failed (exit code 1). Full command was:["rpmbuild", "-bb", "--target", "noarch", "--define", "buildroot /tmp/package-rpm-build-76fe694aabe458704ffc6e0f0b313419f767c0a603c586e623aa7d1d5190/BUILD", "--define", "_topdir /tmp/package-rpm-build-76fe694aabe458704ffc6e0f0b313419f767c0a603c586e623aa7d1d5190", "--define", "_sourcedir /tmp/package-rpm-build-76fe694aabe458704ffc6e0f0b313419f767c0a603c586e623aa7d1d5190", "--define", "_rpmdir /tmp/package-rpm-build-76fe694aabe458704ffc6e0f0b313419f767c0a603c586e623aa7d1d5190/RPMS", "--define", "_tmppath /tmp", "/tmp/package-rpm-build-76fe694aabe458704ffc6e0f0b313419f767c0a603c586e623aa7d1d5190/SPECS/apel-ssm.spec"] {:level=>:error}```

With the verbose mode, this doesn't get much clearer - the only presented failure is logged as 'info' level in FPM and is a changelog error that occurs just after this command is ran.  For additional context, these lines are logged before the failure and after the run of the specific command.

```error: %changelog entries must start with * {:level=>:info}
Building target platforms: noarch {:level=>:info}
Building for target noarch {:level=>:info}```

The error could be terminal, but I have no idea.  Help appreciated.

2024-01-17 11:04 UTC, RedProkofiev commented
Build script is here!  Finally working on EL8 and Debian systems, with service setup.

2024-01-17 11:07 UTC, RedProkofiev commented
For some reason there's still a merge conflict - was the patch reverted?  or is this due to my dev branch not being fast forwarded?

2024-01-17 11:55 UTC, tofu-rocketry commented
> For some reason there's still a merge conflict - was the patch reverted? or is this due to my dev branch not being fast forwarded?

That'll be because we merged the change to the CHANGELOG into the `dev` branch separately. I'll help you sort that out towards the end of the week.

Could you have a look at the code quality checks and see if you can improve that?

2024-01-18 15:40 UTC, tofu-rocketry requested changes

2024-01-26 10:40 UTC, RedProkofiev commented on setup.py
> +              'PyOpenSSL',
It works with either, but the problem here is that the docker build uses the requirements.txt as the install.  Install_requires in setup.py doesn't then go and actually install the missing packages (even though it appears to make a token effort to search for them?) so we simply added the requirements to requirements.txt which solved this

2024-01-26 10:43 UTC, RedProkofiev commented on setup.py
> +              'certifi': ['certifi<2020.4.5.2'],
Done

2024-01-26 10:48 UTC, RedProkofiev commented on setup.py
> -              'daemon': ['python-daemon<=2.3.0'],
It's moved back, and I think you've lodged a commit to ratify where it should be more formally

2024-01-26 13:51 UTC, tofu-rocketry commented on setup.py
> -              'daemon': ['python-daemon<=2.3.0'],
Now sorted.

2024-01-26 13:52 UTC, tofu-rocketry approved these changes

2024-02-06 15:18 UTC, tofu-rocketry approved these changes

2024-02-06 15:32 UTC, merged