Update setup.py to build and install the package underneath
apel/ssm pull request #338
Opened 2024-05-10 14:37 UTC by Sae126V

Now  will make use of build step to install the package and enabling sepeate flows for build and install phases.

2024-05-10 14:51 UTC, tofu-rocketry approved these changes

2024-05-21 09:43 UTC, tofu-rocketry requested changes
Can you squash these commits together, and improve the commit message?

It needs a much better explanation of _why_ this change is needed.

2024-05-21 09:48 UTC, Sae126V commented
> Can you squash these commits together, please, and improve the commit message?
> 
> It needs a much better explanation of _why_ this change is needed.

Hi @tofu-rocketry , 3d48d76c6a1ee115106fb0716ae08bd06f65e42d I think I have updated this? Isn't it useful ?

2024-05-21 15:29 UTC, tofu-rocketry approved these changes

2024-05-21 15:39 UTC, merged